import "./globals.css";
import type { Metadata } from "next";
import Link from "next/link";
import { octokit } from "./octokit";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const reposQuery = await octokit.repos.listForUser({
    username: "facebook",
  });

  return (
    <html lang="en">
      <body>
        <div className="grid grid-cols-[200px_1fr]">
          <aside className="bg-slate-50 h-screen">
            <ul className="space-y-2 p-4">
              {reposQuery.data.map((repo) => (
                <li key={repo.id}>
                  <Link
                    className="hover:underline"
                    href={`/repos/${repo.owner.login}/${repo.name}`}
                  >
                    {repo.name}
                  </Link>
                </li>
              ))}
            </ul>
          </aside>
          <main className="p-4">{children}</main>
        </div>
      </body>
    </html>
  );
}
